### ISSUE TITLE
dachs admin suggestucds errors out unexpectedly (for me)

### ISSUE THREAD

**Issue by ygrange** [gavodachs/dachs-doc#14]
I'm not sure if this is an issue with the documentation or with dachs itself, so I post it as an issue here. I have a bunch of rd files with lots of columns without ucds. I thought being smart by trying out:
`dachs admin suggestucds q#source_catalog` . However, this returns the following error:
```
*X*X* Uncaught exception at toplevel
*** Error: Oops.  Unhandled exception WSDLError.

Exception payload: Missing <definitions> element.
```

I couldn't find the `<definitions>` element anywhere in the documentation, and this error seems not to come from dachs itself either (or at least it is not known to the docmentation). So either this is an issue with dependencies, or some undocumented thing going on. So I thought I better raise it here :)

**Comment by msdemlei** [comment]
On Mon, Apr 12, 2021 at 01:56:32AM -0700, Yan Grange wrote:
> I'm not sure if this is an issue with the documentation or with dachs itself, so I post it as an issue here. I have a bunch of rd files with lots of columns without ucds. I thought being smart by trying out:
> `dachs admin suggestucds q#source_catalog` . However, this returns the following error:
> ```
> *X*X* Uncaught exception at toplevel
> *** Error: Oops.  Unhandled exception WSDLError.
> 
> Exception payload: Missing <definitions> element.
> ```

Ouch.  That's a DaCHS 1, right?

> I couldn't find the `<definitions>` element anywhere in the
> documentation, and this error seems not to come from dachs itself

This is because it's an element from SOAP (see below).

> this is an issue with dependencies, or some undocumented thing
> going on. So I thought I better raise it here :) 

Thanks for doing that, but I think I can't help you other than asking
you to upgrade to a DaCHS 2.

Here's the background:

SOAP is/was a non-VO standard for doing "remote procedure calls", i.e.,
fake some functionality on one host with something that looks like a
function call on another host.  The early VO expected that SOAP would
be the next big thing and planned to employ it left and right.

Fortunately (because SOAP, really, was quite some pain for very
little gain) SOAP fell out of favour in time for us to not base any
significant standard on it (Registry Interfaces 1 fiddled with it,
and in VOSI you sometimes read "REST binding", which can only be
understood in contrast to SOAP).  

DaCHS 1 supported it nevertheless, and I thought it was cute to use
it for the UCD querying done by adm suggestucds.

Of course, SOAP support with twisted and python3 is essentially
non-existing, and so DaCHS 2 currently doesn't do SOAP until that
changes.  Which means that the remote service that dachs adm
suggestucds built on in DaCHS 1 (the Heidelberg DaCHS) can't speak
SOAP any more.  What you're seeing is the python 2 SOAP parser
failing on an error message to that effect that it gets from
Heidelberg.

Given I'd have to port the SOAP library to change that, I don't think
that will change -- as I said, I'm actually quite relieved that
SOAP will be forgotten.  In an emergency, I could backport the
new-style, DaCHS 2 "RPC" method for suggestucds (it's just parsing a
VOTable now) to DaCHS 1, but frankly I... erm... would prefer not to.

So... any chance you can upgrade your development system to DaCHS 2?
The RDs by and large are compatible, so as long as you don't do too
fancy things, you could still deploy on DaCHS 1.

If you go for that, and that fixes your problem: would you close this
bug?

**Comment by ygrange** [comment]
I guess so. Last time we upgraded is a while ago. I just checked and it is indeed a version 1.X dachs instance. I'll keep this in mind when I want to lobby for upgrading :) Thanks for now!
