### ISSUE TITLE
Case sensitive column name

### ISSUE THREAD

**Issue by davepallot** [gavodachs/dachs-doc#21]
My database has uppercase column names but the TAP service is looking for a lower case name, therefore programs like TOPCAT fail with "name does not exist". How do I deal with the situation without changing the database column name to lower case?

**Comment by msdemlei** [comment]
On Mon, Aug 29, 2022 at 01:03:15AM -0700, Dave Pallot wrote:
> My database has uppercase column names but the TAP service is
> looking for a lower case name, therefore programs like TOPCAT fail
> with "name does not exist". How do I deal with the situation
> without changing the database column name to lower case?

I take it you have a table that is not imported through DaCHS, right?

What program do you use to create that table instead?  The best way
(well, after using DaCHS itself to create the table:-) to fix the
situation would be to change the CREATE TABLE statement there to not
use delimited identifiers (with quotes around them).  These are
essentially always painful.  With simple, non-delimited column names,
your problem should go away.

An alternative might be to tell DaCHS to use delimited identifiers.
You do that by writing something like <column
name="quoted/UPPERCASE"/> (i.e., prefix with "quoted/") -- but
that'll suck, because that way people writing TAP queries would have
to say `SELECT "UPPERCASE"...' (with exactly the quotes and the right
case and all).  So, better don't do it.

By the way, for many reasons I much prefer the dachs-support mailing
list,
<https://lists.g-vo.org/cgi-bin/mailman/listinfo/dachs-support>, for
questions like these.

**Comment by chbrandt** [comment]
I understand this issue was solved.
